header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: Recrush Labs
  paths-ignore:
    # Ignore hidden files
    - "**/.*"
    # Ignore LICENSE
    - "LICENSE"
    # Ignore docs and generated files
    - "**/*.md"
    - "**/*.yml"
    - "**/*.yaml"
    - "**/*.toml"
    - "**/*.lock"
    - "target/**"

  comment: on-failure
