name: "Check"
description: "Check will do all essential checks"
inputs:
  github_token:
    description: "Github Token"
    required: true

runs:
  using: "composite"
  steps:
    - name: Check License Header
      uses: apache/skywalking-eyes/header@v0.4.0
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      with:
        log: info

    - name: Format
      shell: bash
      run: cargo fmt --all -- --check

    - name: Doc check
      shell: bash
      run: cargo doc --no-deps --all-features

    - name: Clippy
      shell: bash
      run: cargo clippy --all-targets --all-features -- -D warnings
